### ISSUE TITLE
Async Commands Error

### ISSUE THREAD

**Issue by Spazzinq** [FinalPacket/Siege-Issues#10]
https://gist.github.com/Spazzinq/962994b1d66e94052ad1c677a8ca8bc5

Link for more information inside the error (https://www.spigotmc.org/threads/plugins-triggering-commands-async.31815/)

TacoSpigot 1.8.8
Siege 1.3 Beta

**Comment by FinalPacket** [comment]
I remember these, I have to put them inside a task.
I'll fix that later.

Thank you for reporting the issue.

**Comment by FinalPacket** [comment]
I believe I fixed it. For some reason I haven't gotten this error so far.
