### ISSUE TITLE
Bypasses and FP

### ISSUE THREAD

**Issue by zikdriver** [FinalPacket/Siege-Issues#4]
Bypasses:

Highjump (AAC and DAC)
AirJump
30 Block Step bypass (NCP Mode)
Liquidwalk bypass
Custom Speed bypass: https://i.imgur.com/VXbPuKp.png
Knockback Reducing is work and negative knockback
VClip and HClip is working.
Icespeed is working.

False positives:

From iceblock to a normal block (on running) fp.
Packet legit flag (sometimes)

Testet it with Labymod and Liquidbounce 26.2

**Comment by FinalPacket** [comment]
When does the Packet legit flag happen?
