### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Spazzinq** [FinalPacket/Siege-Issues#6]
Please help me I am getting an error when I try to use your plugin. I think I'm just being retarded (just a note)

https://gist.github.com/Spazzinq/841f1f39aed31e74135f2b7c2aa8ac1d
(I tried this with ProtocolLib 4.2.0, 4.2.1, and 4.3.0)

Thanks,
Spazzinq

**Comment by FinalPacket** [comment]
I'm an idiot, I fixed this a long time ago. But I have been rewriting and learning stuff.

**Comment by Spazzinq** [comment]
Are you going to post a fix for this lol

**Comment by FinalPacket** [comment]
I did?
