### ISSUE TITLE
Fly & MorePackets False Positive

### ISSUE THREAD

**Issue by Spazzinq** [FinalPacket/Siege-Issues#9]
When I fly, I get flagged for speed and fly. Also, one time when I logged on I got flagged 10VL for MorePackets.

It may be because these packets are not supported:
https://gist.github.com/Spazzinq/87f2f4526e11e8b845a359fc85a814e2

TacoSpigot 1.8.8
Siege 1.3 Beta

**Comment by Spazzinq** [comment]
You should add an option to disable the animation and disable the ban message.

**Comment by FinalPacket** [comment]
There is an option, look in config.yml and you can remove or add commands to when they are banned.
I have also addressed the fly and morepackets on join.

**Comment by Spazzinq** [comment]
I still get flagged for fly.
